use crate::recursos::dto::{
    CreateEquipamientoRequest, CreateFinanciamientoRequest, CreatePatenteRequest,
    CreateProductoRequest, EquipamientoDto, FinanciamientoDto, PatenteDto, ProductoDto,
    UpdateEquipamientoRequest, UpdateFinanciamientoRequest, UpdatePatenteRequest,
    UpdateProductoRequest,
};
use crate::recursos::models::{Equipamiento, Financiamiento, Patente, Producto};

impl_resource_repository!(
    Patente,
    PatenteDto,
    CreatePatenteRequest,
    UpdatePatenteRequest,
    "patentes",
    id_patente,
    create_patente,
    get_patentes_by_proyecto,
    get_patente_by_id,
    update_patente,
    delete_patente,
    delete_patentes_by_proyecto,
    reactivate_patente,
    "Patente no encontrada.",
    titulo,
    numero_patente,
    tipo,
    estado,
    fecha_solicitud,
    fecha_concesion,
    pais,
    entidad_concedente,
    descripcion
);

impl_resource_repository!(
    Producto,
    ProductoDto,
    CreateProductoRequest,
    UpdateProductoRequest,
    "productos",
    id_producto,
    create_producto,
    get_productos_by_proyecto,
    get_producto_by_id,
    update_producto,
    delete_producto,
    delete_productos_by_proyecto,
    reactivate_producto,
    "Producto no encontrado.",
    nombre,
    tipo,
    etapa,
    descripcion,
    fecha_registro
);

impl_resource_repository!(
    Equipamiento,
    EquipamientoDto,
    CreateEquipamientoRequest,
    UpdateEquipamientoRequest,
    "equipamientos",
    id_equipamiento,
    create_equipamiento,
    get_equipamientos_by_proyecto,
    get_equipamiento_by_id,
    update_equipamiento,
    delete_equipamiento,
    delete_equipamientos_by_proyecto,
    reactivate_equipamiento,
    "Equipamiento no encontrado.",
    nombre,
    descripcion,
    especificaciones,
    valor_estimado,
    moneda,
    proveedor,
    fecha_adquisicion
);

impl_resource_repository!(
    Financiamiento,
    FinanciamientoDto,
    CreateFinanciamientoRequest,
    UpdateFinanciamientoRequest,
    "financiamientos",
    id_financiamiento,
    create_financiamiento,
    get_financiamientos_by_proyecto,
    get_financiamiento_by_id,
    update_financiamiento,
    delete_financiamiento,
    delete_financiamientos_by_proyecto,
    reactivate_financiamiento,
    "Financiamiento no encontrado.",
    entidad_financiadora,
    tipo,
    monto,
    moneda,
    fecha_inicio,
    fecha_fin,
    descripcion,
    estado_financiero
);
