use crate::recursos::dto::{
    CreateEquipamientoRequest, CreateFinanciamientoRequest, CreatePatenteRequest, EquipamientoDto,
    FinanciamientoDto, PatenteDto, UpdateEquipamientoRequest, UpdateFinanciamientoRequest,
    UpdatePatenteRequest,
};
use crate::recursos::models::{Equipamiento, Financiamiento, Patente};

impl_resource_repository!(
    Patente,
    PatenteDto,
    CreatePatenteRequest,
    UpdatePatenteRequest,
    "patentes",
    id_patente,
    create_patente,
    get_patentes_by_proyecto,
    get_patente_by_id,
    update_patente,
    delete_patente,
    reactivate_patente,
    "Patente no encontrada.",
    titulo,
    numero_patente,
    tipo,
    estado,
    fecha_solicitud,
    fecha_concesion,
    pais,
    entidad_concedente,
    descripcion,
    clasificacion_ipc,
    id_org_unit_concedente
);

impl_resource_repository!(
    Equipamiento,
    EquipamientoDto,
    CreateEquipamientoRequest,
    UpdateEquipamientoRequest,
    "equipamientos",
    id_equipamiento,
    create_equipamiento,
    get_equipamientos_by_proyecto,
    get_equipamiento_by_id,
    update_equipamiento,
    delete_equipamiento,
    reactivate_equipamiento,
    "Equipamiento no encontrado.",
    nombre,
    descripcion,
    especificaciones,
    valor_estimado,
    moneda,
    proveedor,
    fecha_adquisicion,
    codigo_institucional,
    tipo_equipamiento,
    uso_equipamiento,
    id_org_unit_propietaria,
    id_financiamiento
);

impl_resource_repository!(
    Financiamiento,
    FinanciamientoDto,
    CreateFinanciamientoRequest,
    UpdateFinanciamientoRequest,
    "financiamientos",
    id_financiamiento,
    create_financiamiento,
    get_financiamientos_by_proyecto,
    get_financiamiento_by_id,
    update_financiamiento,
    delete_financiamiento,
    reactivate_financiamiento,
    "Financiamiento no encontrado.",
    entidad_financiadora,
    tipo,
    monto,
    moneda,
    fecha_inicio,
    fecha_fin,
    descripcion,
    estado_financiero
);
